sudo: false

dist: trusty

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

language: php
php:
  - nightly
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

matrix:
  allow_failures:
    - php: nightly
      
services: mongodb

before_script:
  - PHP_VERSION=$(php -r 'echo phpversion();')
  - phpunit --version
  - mongod --version
  - mkdir -p ./share
  - echo $TRAVIS_PHP_VERSION
  - echo $PHP_VERSION
  - if [[ ${PHP_VERSION:0:2} == "5." ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${PHP_VERSION:0:2} == "7." ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer update --no-interaction
  - if [[ ${PHP_VERSION:0:2} == "7." ]]; then composer require "alcaeus/mongo-php-adapter"; fi
  
script:
  - composer cover
  
after_script:
  - composer check-style
  - composer coveralls
