language: php

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: nightly
      
services: mongodb

before_script:
  - PHP_VERSION=$(php -r 'echo phpversion();')
  - phpunit --version
  - mongod --version
  - mkdir -p ./share
  - echo $TRAVIS_PHP_VERSION
  - echo $PHP_VERSION
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update --no-interaction
  - composer require "alcaeus/mongo-php-adapter"
  
script:
  - composer cover
  
after_script:
  - composer check-style
  - composer coveralls
